// Define macros for features to support generic DirectorExceptions
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_FROM_TARGET_HANDLING(METHOD)
%feature("director:except") METHOD %{
  jthrowable $error = jenv->ExceptionOccurred();
  if ($error) {
    jenv->ExceptionClear();
    throw Swig::DirectorException(jenv,$error);
  }
%}
%enddef
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING_WITH_THROWS(METHOD,JAVA_EXCEPTIONS...)
SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING_INTERNAL(METHOD,"except",throws= ## #JAVA_EXCEPTIONS)
%enddef
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING(METHOD)
SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING_INTERNAL(METHOD,"except")
%enddef
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING_INTERNAL(METHOD,FEATURE_ATTRS...)
%feature(FEATURE_ATTRS) METHOD %{
  try { $action }
  catch (Swig::DirectorException & direxcp) {
    direxcp.raiseJavaException(jenv);
    return $null;
  }
%}
%enddef
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_HANDLING(METHOD)
SWIG_GENERIC_DIRECTOR_EXCEPTION_FROM_TARGET_HANDLING(METHOD)
SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING(METHOD)
%enddef
%define SWIG_GENERIC_DIRECTOR_EXCEPTION_HANDLING_WITH_THROWS(METHOD,JAVA_EXCEPTIONS...)
SWIG_GENERIC_DIRECTOR_EXCEPTION_FROM_TARGET_HANDLING(METHOD)
SWIG_GENERIC_DIRECTOR_EXCEPTION_TO_TARGET_HANDLING_WITH_THROWS(METHOD,JAVA_EXCEPTIONS)
%enddef
